apiVersion: apps/v1
kind: Deployment
metadata:
    name: planification-microservice
    namespace: garage-workflow
spec:
    replicas: 1
    selector:
        matchLabels:
            app: planification-microservice
            version: v1
    template:
        metadata:
            labels:
                app: planification-microservice
                version: v1
        spec:
            containers:
                - name: planification-microservice
                  image: garage-workflow-planification-microservice:latest
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 5003
                  env:
                      - name: RABBITMQ_URL
                        value: amqp://rabbitmq
                      - name: CLIENT_API_URL
                        value: http://client-microservice:5001
                      - name: VEHICLE_API_URL
                        value: http://vehicle-microservice:5002
                      - name: INVOICE_API_URL
                        value: http://invoice-microservice:5004
---
apiVersion: v1
kind: Service
metadata:
    name: planification-microservice
    namespace: garage-workflow
spec:
    selector:
        app: planification-microservice
    ports:
        - protocol: TCP
          port: 5003
          targetPort: 5003
    type: ClusterIP
