version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - CLIENT_API_URL=http://client-microservice:5001
      - VEHICLE_API_URL=http://vehicle-microservice:5002
      - MAINTENANCE_TASKS_API_URL=http://planification-microservice:5003
      - INVOICE_API_URL=http://invoice-microservice:5004
    depends_on:
      - client-microservice
      - vehicle-microservice
      - planification-microservice
      - invoice-microservice

  client-microservice:
    build:
      context: ./client-microservice
    ports:
      - "5001:5001"

  vehicle-microservice:
    build:
      context: ./vehicle-microservice
    ports:
      - "5002:5002"

  planification-microservice:
    build:
      context: ./planification-microservice
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - RABBITMQ_URL=amqp://rabbitmq
      - CLIENT_API_URL=http://client-microservice:5001
      - VEHICLE_API_URL=http://vehicle-microservice:5002
      - INVOICE_API_URL=http://invoice-microservice:5004
    depends_on:
      - rabbitmq
      - client-microservice
      - vehicle-microservice
      - invoice-microservice

  notification-microservice:
    build:
      context: ./notification-microservice
    volumes:
      - shared-data:/app/shared
    ports:
      - "5005:5005"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - rabbitmq

  invoice-microservice:
    build:
      context: ./invoice-microservice
    volumes:
      - shared-data:/app/shared
    ports:
      - "5004:5004"
    environment:
      - PORT=5004
      - RABBITMQ_URL=amqp://rabbitmq
      - CLIENT_API_URL=http://client-microservice:5001
      - VEHICLE_API_URL=http://vehicle-microservice:5002
    depends_on:
      - rabbitmq
      - client-microservice
      - vehicle-microservice

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_GATEWAY_URL=http://localhost:4000
    depends_on:
      - api-gateway

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # AMQP port for RabbitMQ
      - "15672:15672"  # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  shared-data: