apiVersion: v1
kind: PersistentVolume
metadata:
    name: shared-data-pv
    namespace: garage-workflow
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    hostPath:
        path: /tmp/shared-data
