apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
    name: api-gateway
    namespace: garage-workflow
spec:
    hosts:
        - api-gateway
    http:
        - route:
              - destination:
                    host: api-gateway
                    subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
    name: api-gateway
    namespace: garage-workflow
spec:
    host: api-gateway
    trafficPolicy:
        connectionPool:
            tcp:
                maxConnections: 1
            http:
                http1MaxPendingRequests: 1
                maxRequestsPerConnection: 1
        outlierDetection:
            consecutiveErrors: 1
            interval: 1s
            baseEjectionTime: 3m
            maxEjectionPercent: 100
    subsets:
        - name: v1
          labels:
              version: v1
