apiVersion: apps/v1
kind: Deployment
metadata:
    name: api-gateway
    namespace: garage-workflow
spec:
    replicas: 1
    selector:
        matchLabels:
            app: api-gateway
    template:
        metadata:
            labels:
                app: api-gateway
        spec:
            containers:
                - name: api-gateway
                  image: garage-workflow-api-gateway:latest
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 4000
                  env:
                      - name: CLIENT_API_URL
                        value: http://client-microservice:5001
                      - name: VEHICLE_API_URL
                        value: http://vehicle-microservice:5002
                      - name: MAINTENANCE_TASKS_API_URL
                        value: http://planification-microservice:5003
                      - name: INVOICE_API_URL
                        value: http://invoice-microservice:5004
---
apiVersion: v1
kind: Service
metadata:
    name: api-gateway
    namespace: garage-workflow
spec:
    selector:
        app: api-gateway
    ports:
        - protocol: TCP
          port: 4000
          targetPort: 4000
          nodePort: 30001 # Use a fixed NodePort
    type: NodePort
