apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend
    namespace: garage-workflow
spec:
    replicas: 2
    selector:
        matchLabels:
            app: frontend
            version: v1
    template:
        metadata:
            labels:
                app: frontend
                version: v1
        spec:
            containers:
                - name: frontend
                  image: garage-workflow-frontend:latest
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 3000
                  env:
                      - name: REACT_APP_API_GATEWAY_URL
                        value: http://192.168.42.130:30001
---
apiVersion: v1
kind: Service
metadata:
    name: frontend
    namespace: garage-workflow
spec:
    selector:
        app: frontend
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
    type: LoadBalancer
