apiVersion: apps/v1
kind: Deployment
metadata:
    name: invoice-microservice
    namespace: garage-workflow
spec:
    replicas: 1
    selector:
        matchLabels:
            app: invoice-microservice
            version: v1
    template:
        metadata:
            labels:
                app: invoice-microservice
                version: v1
        spec:
            containers:
                - name: invoice-microservice
                  image: garage-workflow-invoice-microservice:latest
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 5004
                  env:
                      - name: RABBITMQ_URL
                        value: amqp://rabbitmq
                      - name: CLIENT_API_URL
                        value: http://client-microservice:5001
                      - name: VEHICLE_API_URL
                        value: http://vehicle-microservice:5002
                  volumeMounts:
                      - name: shared-data
                        mountPath: /app/shared
            volumes:
                - name: shared-data
                  persistentVolumeClaim:
                      claimName: shared-data-pvc
---
apiVersion: v1
kind: Service
metadata:
    name: invoice-microservice
    namespace: garage-workflow
spec:
    selector:
        app: invoice-microservice
    ports:
        - protocol: TCP
          port: 5004
          targetPort: 5004
    type: ClusterIP
