apiVersion: apps/v1
kind: Deployment
metadata:
    name: notification-microservice
    namespace: garage-workflow
spec:
    replicas: 2
    selector:
        matchLabels:
            app: notification-microservice
            version: v1
    template:
        metadata:
            labels:
                app: notification-microservice
                version: v1
        spec:
            containers:
                - name: notification-microservice
                  image: garage-workflow-notification-microservice:latest
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 5005
                  env:
                      - name: RABBITMQ_URL
                        value: amqp://rabbitmq
                      - name: EMAIL
                        value: "najiiilyassoo@gmail.com"
                      - name: PASSWORD
                        value: "wedy hran twaw fwal"
                  volumeMounts:
                      - name: shared-data
                        mountPath: /app/shared
            volumes:
                - name: shared-data
                  persistentVolumeClaim:
                      claimName: shared-data-pvc
---
apiVersion: v1
kind: Service
metadata:
    name: notification-microservice
    namespace: garage-workflow
spec:
    selector:
        app: notification-microservice
    ports:
        - protocol: TCP
          port: 5005
          targetPort: 5005
    type: ClusterIP
