apiVersion: apps/v1
kind: Deployment
metadata:
    name: planification-microservice
    namespace: garage-workflow
spec:
    replicas: 2
    selector:
        matchLabels:
            app: planification-microservice
            version: v1
    template:
        metadata:
            labels:
                app: planification-microservice
                version: v1
        spec:
            containers:
                - name: planification-microservice
                  image: garage-workflow-planification-microservice:latest
                  ports:
                      - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
    name: planification-microservice
    namespace: garage-workflow
spec:
    selector:
        app: planification-microservice
    ports:
        - protocol: TCP
          port: 5003
          targetPort: 5003
    type: ClusterIP
