apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: shared-data-pvc
    namespace: garage-workflow
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 1Gi
